### ISSUE TITLE
Download exercise files

### ISSUE THREAD

**Issue by AlfalfaAnne** [HackerYou/chalk#164]
Since there is no central zip file to download all the exercise files for a class, I've been adding [download file] to the end of all the files that can be downloaded - that way they can just do a search in the page and download.

If anyone else has another suggestion - but just as a heads up that I'm adding this to the notes.

Thanks!

**Comment by Rchristiani** [comment]
So the idea is that there is a link at the top of each lesson, that would all the user to DL any exercise files from the lesson.  This is really a usability issue, since this exsisted before and it was not really that apparent on redesign that that was used so much.

This would involve some sort of system where you could either:

A) On the lesson page, add a new field for a file that is attached to the lesson that represents a zip of files
B) Figure out a way to look through the file and parse out exercise files and when the lesson is updated create the zip on the server, upload to AWS and add as a link in the top.
C) Have a topic for the lesson where you just add the files.
D) ...?

Thoughts on what the best solution might be @kristencodes, @swbloom, @sylvianguy?

**Comment by swbloom** [comment]
My instinct is that B, while being the nicest and most dynamic, runs the risk of producing the most unforseen bugs/edge cases in actual implementation. For example, would we be limited in what file types the server was able to parse? Would it be challenging for the server to know how to build an appropriate folder structure for our exercises? What if we want certain files not to be included in the bundle?

The huge plus for B is that it would mean not needing to rebundle every time we upload a new file to the lesson, but I'm not 100% convinced this outweighs the dev overhead to make it work. It's a node thing, so y'all probably have more experience with this than me.

My only concern with Option C is that it isn't intuitive. My brain doesn't automatically associate adding a 'download all' section with adding a 'topic'.  This could be solved in like a FAQ/the docs, though.

So I think right now I'm going to vote for option A, since I can't think of anything better :8ball:

**Comment by Rchristiani** [comment]
I think for now we will do option A, since that seems the least buggy. But it would be nice to have some system in the future that would smartly gather the exercises added and zip them up for you.

**Comment by AlfalfaAnne** [comment]
As a temporary measure, I've been creating a new topic that I add to the lesson. :)

**Comment by Rchristiani** [comment]
I have implemented option A. It was the easiest at the moment.
